# Generated by Django 4.2.4 on 2023-08-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='tiempo_entrenando',
            new_name='experiencia_entrenando',
        ),
    ]
