# Generated by Django 4.2.4 on 2023-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tiempo_entrenando_estudiante_experiencia_entrenando'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='objetivo_conseguido',
            field=models.BooleanField(default=False),
        ),
    ]
