# Generated by Django 4.2.4 on 2023-08-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_estudiante_objetivo_conseguido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='estado',
            new_name='estado_fisico',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nivel',
            new_name='nivel_fitness',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='carrera',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='correo_electronico',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='facultad',
            field=models.CharField(max_length=70),
        ),
    ]
