# Generated by Django 4.2.4 on 2023-08-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_estado_estudiante_estado_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_fisico',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='imc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_fitness',
            field=models.CharField(choices=[('1', 'Novato'), ('2', 'Intermedio'), ('3', 'Avanzado')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='objetivo_conseguido',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='recomendacion_entrenamiento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='recomendacion_peso',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
