# Generated by Django 4.2.4 on 2023-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_estudiante_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='objetivo_conseguido',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='objetivo_conseguido2',
            field=models.BooleanField(default=False),
        ),
    ]
