# Generated by Django 4.2.4 on 2023-08-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_objetivo_conseguido2_estudiante_objetivo_conseguido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.entrenador'),
        ),
    ]
