# Generated by Django 4.2.4 on 2023-08-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_estudiante_entrenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='experiencia_entrenando',
            field=models.IntegerField(null=True),
        ),
    ]
