# Generated by Django 4.2.4 on 2023-08-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_estudiante_experiencia_entrenando'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='experiencia_entrenando',
            new_name='meses_entrenando',
        ),
    ]
