# Generated by Django 4.2.4 on 2023-08-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_rename_experiencia_entrenando_estudiante_meses_entrenando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='recomendacion_entrenamiento',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
