# Generated by Django 4.2.4 on 2023-08-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_estudiante_fecha_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
    ]
